### ISSUE TITLE
Do you have any plans when to open source the code？

### ISSUE THREAD

**Issue by zhangzscn** [aislabunimi/ROSE2#1]

**Comment by goldleaf3i** [comment]
Hi,
in the next couple of weeks hopefully.
The code is already open source on the old repo here
https://github.com/goldleaf3i/declutter-reconstruct

here we will publish the updated version that is integrated with ROS

**Comment by goldleaf3i** [comment]
We release the first version of the code. More documentation is arriving soon, but now the package can be used and tested. Let me know if you need something else.
