### ISSUE TITLE
Questions about how to get the room segmentation result

### ISSUE THREAD

**Issue by B0GGY** [aislabunimi/ROSE2#2]
Hi, thanks for your work. I am wondering how could I save the room segmentation result like Fig5 from the paper 'Robust structure identification and room segmentation of cluttered indoor environments from occupancy grid map' as a png image.

**Comment by goldleaf3i** [comment]
Hi, if you are working with images as input, and you are not using the method online as embedded with ROS, you can use the old version of the code (here https://github.com/goldleaf3i/declutter-reconstruct) that saves the image. Also, you can find there how to save such a file. there is a function that does what you need. 

The code of the two repo is basically the same, this one is a little more commented, updated, and integrated with ros.
I can look into it later this week to give more details if you need them

**Comment by B0GGY** [comment]
I tried the code from  https://github.com/goldleaf3i/declutter-reconstruct, but it says ModuleNotFoundError: No module named 'fft_structure_extraction'. So I found one from https://github.com/tkucner/rose/blob/master/fft_structure_extraction.py. However, it seems that some methods and attributes are missing, like show() and generate_initial_hypothesis_simple().

**Comment by Nisici** [comment]
Hello, you can get the room segmentation result as a png image launching voronoi.launch file, it will store outputs in the folder src/rose_v2_repo/map_processing. It's going to be slower than the method using ROSE.launch because it's doing postprocessing using voronoi method that finds more rooms.

**Comment by B0GGY** [comment]
Thanks a lot, it works!
