### ISSUE TITLE
Segment rooms incorrectly

### ISSUE THREAD

**Issue by gaojunjie1999** [aislabunimi/ROSE2#3]
thank you for your work, I'm trying to build the layout using my input occupancy map. The extended lines and edges seem to be generated correctly. However, some rooms are left out in the outcome, and only half of some rectangle rooms are detected, which gives a result of triangle-shaped room outcome. Could you please tell me how I can correct this?

**Comment by gaojunjie1999** [comment]
It seems that the second problem  dues to jsk_recognition_msgs/polygon visualizattion

**Comment by Nisici** [comment]
Hello, as you pointed out correctly the second issue is due to jsk-rviz-plugins that fails to visualize some of the rooms as quadrilaterals and instead draws them as triangles. If you want to detect more rooms and also visualize them in jpg/pdf files you should go to the launch file and change the parameter _rooms_voronoi_ to **True** (or launch [voronoi.launch](https://github.com/aislabunimi/ROSE2/blob/main/launch/voronoi.launch)). 
You will see the results in the folder src/rose_v2_repo/map_processing.

**Comment by gaojunjie1999** [comment]
thanks, it works better with Voronoi. But the step to distinguish cells_out seem to eliminate more cells than expected, is this because I didn't extract the contour properly?

**Comment by goldleaf3i** [comment]
Hi, yes we use the contour to filter out cells that are outside of the map. if you share the results in the map_processing folder we can have a further look about that

**Comment by gaojunjie1999** [comment]
Thanks for your time, now I make sure the contour I use is the largest contour(in blue), but some rooms inside the contour seem to be eliminated. And some room outside the contour is kept as the outcome (like the pink one on the top right)
![Screenshot from 2023-08-03 21-04-39](https://github.com/aislabunimi/ROSE2/assets/74496687/b3b86317-597f-43ed-8101-03a502d64d96)

**Comment by gaojunjie1999** [comment]
I tried to run with voronoi, and the result looks like this, is this still because I was using the wrong contour?
![8b_rooms_th1_on_map](https://github.com/aislabunimi/ROSE2/assets/74496687/d25be83e-d9b2-46ad-ba18-627933a4439e)

**Comment by Nisici** [comment]
First you should look at the file _8b_rooms_th1_on_map_post_ for a better visualization. The problem could be that the method is not considering enough lines and therefore it can't detect some rooms. You could try changing the _spatialClusteringLineSegmentsThreshold_ parameter in the launch file. 
Also if you send me the image of the occupancygrid I can try to solve the problem.

**Comment by goldleaf3i** [comment]
are you sure about the scale of the map? the grid on the top right of the first image seems very tiny, is it possible that you are plotting this environment in a 2x or 3x scale wrt its original size?

**Comment by gaojunjie1999** [comment]
thanks, there existed an offset between the real contour and the contour I used, and I changed the param in the launch file and it did work better.
